# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3e7128e430bed43f40e6555119a5ccb2ccc13038194af7a20eea79dca10ca7b44d7f7c11d508e413b28f651e4829a12805ad65134dd8531d7383d3d83ed26aa

test:
  secret_key_base: 839b544ab13f2ff875f530944d1cfaa9aef53178146bf24362194fbfbb19121fc89f63c25a24fe3496a87bf6905619c7ff91ea534db69cf87bd9c3b0d8a29e0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
